language: python
before_install:
  - sudo apt-get update
services:
  - docker
python:
- '3.6'
install:
- pip install checkov awscli
script:
- scripts/checkov.sh
- scripts/iam_check.sh
- scripts/drift_checks.sh
env:
  global:
  - secure: RUTSGPxPFgvMyxhFR+MC7LCv/h9+wRUdz1r2sSROh+PVUEb6SiNr1++1AcUIA0z3jYH6IDyl+ZGKLtcuseP3I1HbTD45wAZt4bRNUh6tZPYCQJmZyZKms/AUn+jFk3cYX73cv1IUs4Ywumpu68GvAeRgU8IGbucSq0XQaUizARl/PhA+n3swZYwSy8kTBTLGhoQNe71yfJHmAV27eoY3LDzNyftFuGWHm4AF3J2OdfH/CeVBe2hddnWfLtJLafuzCG39xKJrn9S5PyXzw55PHnSj8ytjXU/14CiITxeAW7fF3Xde8HpHOf1A8xrTcE+pti0BKgLNR2o/XVYv5wnuA6+M8s6V0b/aYq0SmIiZohvGn8oh9IFHjHVQZrNAUU17Lf821lvWQluMwPREZC9oRnqjO8WWoTsPgiaGMih/dBDoKHv+dmtnC0kMu0fYVlq4VYwrCQji/AznyXUMlRHaC9sGWg650fGcdebKHOl3Sq65Nf1AmC0QgKojrnOPNHQ55WToktCU6oHsuyjb8p+zt5nuCw+FJp5+BWuXFgqPwrXRMJLaFHKKnl+s2yyXf6kb4PYJC9jGDWUvzWElmDtaEvWfowy0BHkqmYzj0omjlu3e8B+fn9xRlDG3sV9wZhGhbxzDZtc4RDwoIGKTZgIQAhzB3xwuuGEG6gAZOVNtqPU=
  - secure: DQ4UdDgDa9zii79jRGBfPAzHlmgcW7l7B7ALP7yw1V+fxWvfvN9PpWSfoDTPE8/AtzyonUjVPybXzbbrGJljKcrNtNkT7wZRBNbv+5JCehA3inwMUU6G5u4fO3+w+C8Uh3MFFImt/Y+d/TX/3JB+qCNBuI2oGNLtQeOAc8sl+dCJUUQi608VM86jR2tVztsop5BSybhkvoqn4Wxm0TbbNxagIVFceT9MHPphX504Xqs7tPjYFjM2aje5clnYQ7gQrPPmJ+7osOXY42qT3kXPr6vgfk8FgJdbWOpzYNCiXLACapy/nypg3Abv8RnQypMRE3cJp9IGgdVdUwpvfhnSzdsIhCgamNoo0CUIXCkjziA58BFM5UpSddtMavi5fvNYhpD5+7fJWKo5yFSIkDgcXsHm3E8RxQJViRDKHK8eqOxlt05CUPfR5zcaZ4qwQXNrh/1uIof9t/h5wzDh++q1efLrWVjb8gDhX58njpaBGJQIYENe1iYv3E4JDQfDtobmyFYWO5iaG4hlyezZWOvYY8M7k9Wym3DNLNAHIBoUd3mCELtgOomgPB7uojM8siEbQRSgp5iNLJBaeeZQGxIeS23fx8dTZQywvB7/Wh3kb/6UUlPYOfQbu0jkYXVMuIFm6Gvji6x+EAqolWjhGi5+39adGLV0EZhLTM5OGuM6+yk=
